<?xml version="1.0"?>
<!DOCTYPE feature_key_file [
   <!ELEMENT feature_key_file (comments, feature+)>
   <!ELEMENT comments (#PCDATA)>
   <!ELEMENT feature (name, code?, description?, is_sequential, parallel_dimensions, extractor?)>
   <!ELEMENT name (#PCDATA)>
   <!ELEMENT code (#PCDATA)>
   <!ELEMENT description (#PCDATA)>
   <!ELEMENT is_sequential (#PCDATA)>
   <!ELEMENT parallel_dimensions (#PCDATA)>
   <!ELEMENT extractor (#PCDATA)>
]>

<feature_key_file>

   <comments></comments>

   <feature>
      <name>Basic Pitch Histogram</name>
      <code>P-1</code>
      <description>A feature vector consisting of bin magnitudes of the basic pitch histogram described in the jSymbolic manual. Each bin corresponds to one of the 128 MIDI pitches, ordered from lowest to highest, and with an interval of a semitone between each (enharmonic equivalents are assigned the same pitch number). Bin 60 corresponds to middle C. The magnitude of of each bin is proportional to the the number of times notes occurred at the bin's pitch in the piece, relative to all other pitches in the piece (the histogram is normalized).</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>128</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Pitch Class Histogram</name>
      <code>P-2</code>
      <description>A feature vector consisting of bin magnitudes of the pitch class histogram described in the jSymbolic manual. Each bin corresponds to one of the 12 pitch classes, ordered in increasing pitch with an interval of a semitone between each (enharmonic equivalents are assigned the same pitch class number). The first bin corresponds to the most common pitch class in the piece under consideration (it does NOT correspond to a set pitch class). The magnitude of of each bin is proportional to the the number of times notes occurred at the bin's pitch class in the piece, relative to all other pitch classes in the piece (the histogram is normalized).</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>12</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Folded Fifths Pitch Class Histogram</name>
      <code>P-3</code>
      <description>A feature vector consisting of bin magnitudes of the folded fifths pitch class histogram described in the jSymbolic manual. Each bin corresponds to one of the 12 pitch classes, and the bins are ordered such that adjacent bins are separated by an ascending perfect fifth. Bin 0 corresponds to C. Enharmonic equivalents are assigned the same pitch class number. The magnitude of of each bin is proportional to the the number of times notes occurred at the bin's pitch class in the piece, relative to all other pitch classes in the piece (the histogram is normalized).</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>12</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Number of Pitches</name>
      <code>P-4</code>
      <description>Number of unique pitches that occur at least once in the piece. Enharmonic equivalents are grouped together for the purpose of this calculation.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Number of Pitch Classes</name>
      <code>P-5</code>
      <description>Number of pitch classes that occur at least once in the piece. Enharmonic equivalents are grouped together for the purpose of this calculation.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Number of Common Pitches</name>
      <code>P-6</code>
      <description>Number of unique pitches that account individually for at least 9% of all notes. Enharmonic equivalents are grouped together for the purpose of this calculation.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Number of Common Pitch Classes</name>
      <code>P-7</code>
      <description>Number of pitch classes that account individually for at least 20% of all notes. Enharmonic equivalents are grouped together for the purpose of this calculation.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Range</name>
      <code>P-8</code>
      <description>Difference in semitones between the highest and lowest pitches.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Importance of Bass Register</name>
      <code>P-9</code>
      <description>Fraction of notes between MIDI pitches 0 and 54.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Importance of Middle Register</name>
      <code>P-10</code>
      <description>Fraction of notes between MIDI pitches 55 and 72.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Importance of High Register</name>
      <code>P-11</code>
      <description>Fraction of notes between MIDI pitches 73 and 127.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Dominant Spread</name>
      <code>P-12</code>
      <description>Largest number of consecutive pitch classes separated by perfect 5ths that each individually account for at least 9% of the total notes in the piece.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Strong Tonal Centres</name>
      <code>P-13</code>
      <description>Number of isolated peaks in the fifths pitch histogram that each individually account for at least 9% of all notes in the piece.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Mean Pitch</name>
      <code>P-14</code>
      <description>Mean MIDI pitch value, averaged across all pitched notes in the piece. Set to 0 if there are no pitched notes.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Mean Pitch Class</name>
      <code>P-15</code>
      <description>Mean pitch class value, averaged across all pitched notes in the piece. A value of 0 corresponds to a mean pitch class of C, and pitches increase chromatically by semitone in integer units from there (e.g. a value of 2 would mean that D is the mean pitch class). Enharmonic equivalents are treated as a single pitch class.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Most Common Pitch</name>
      <code>P-16</code>
      <description>MIDI pitch value of the most frequently occuring pitch.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Most Common Pitch Class</name>
      <code>P-17</code>
      <description>The pitch class that occurs most frequently compared to other pitch classes. A value of 0 corresponds to C, and pitches increase chromatically by semitone in integer untis (e.g. a value of 2 would mean that D is the most common pitch class). Enharmonic equivalents are treated as a single pitch class.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Prevalence of Most Common Pitch</name>
      <code>P-18</code>
      <description>Fraction of notes that correspond to the most common pitch.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Prevalence of Most Common Pitch Class</name>
      <code>P-19</code>
      <description>Fraction of notes that correspond to the most common pitch class.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Relative Prevalence of Top Pitches</name>
      <code>P-20</code>
      <description>Relative frequency of the second most common pitch in the piece, divided by the relative frequency of the most common pitch.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Relative Prevalence of Top Pitch Classes</name>
      <code>P-21</code>
      <description>Relative frequency of the of the second most common pitch class in the piece, divided by the relative frequency of the most common pitch class.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Interval Between Most Prevalent Pitches</name>
      <code>P-22</code>
      <description>Absolute value of the difference (in semitones) between the pitches of the two most frequently occurring pitches.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Interval Between Most Prevalent Pitch Classes</name>
      <code>P-23</code>
      <description>Absolute value of the difference (in semitones) between the pitches of the two most frequently occurring pitch classes.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Pitch Variability</name>
      <code>P-24</code>
      <description>Standard deviation of the MIDI pitches of all pitched notes in the piece. Provides a measure of how close the pitches as a whole are to the mean pitch.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Pitch Class Variability</name>
      <code>P-25</code>
      <description>Standard deviation of the pitch classes (where 0 corresponds to C, 1 to C#/Db, etc.) of all pitched notes in the piece. Provides a measure of how close the pitch classes as a whole are to the mean pitch class.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Pitch Class Variability After Folding</name>
      <code>P-26</code>
      <description>Standard deviation of the pitch classes in the piece after being folded by perfect fifths as described for the folded fifths pitch class histogram. Provides a measure of how close the pitch classes are as a whole from the mean pitch class from a dominant-tonic perspective.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Pitch Skewness</name>
      <code>P-27</code>
      <description>Skewness of the MIDI pitches of all pitched notes in the piece. Provides a measure of how asymmetrical the pitch distribution is to either the left or the right of the mean pitch. A value of zero indicates no skew.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Pitch Class Skewness</name>
      <code>P-28</code>
      <description>Skewness of the pitch classes (where 0 corresponds to C, 1 to C#/Db, etc.) of all pitched notes in the piece. Provides a measure of how asymmetrical the pitch class distribution is to either the left or the right of the mean pitch class. A value of zero indicates no skew.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Pitch Class Skewness After Folding</name>
      <code>P-29</code>
      <description>Skewness of the pitch classes (where 0 corresponds to C, 1 to C#/Db, etc.) of all pitched notes in the piece. Provides a measure of how asymmetrical the pitch class distribution is to either the left or the right of the mean pitch class. A value of zero indicates no skew.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Pitch Kurtosis</name>
      <code>P-30</code>
      <description>Kurtosis of the MIDI pitches of all pitched notes in the piece. Provides a measure of how peaked or flat the pitch distribution is. The higher the kurtosis, the more the pitches are clustered near the mean and the fewer outliers there are.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Pitch Class Kurtosis</name>
      <code>P-31</code>
      <description>Kurtosis of the pitch classes (where 0 corresponds to C, 1 to C#/Db, etc.) of all pitched notes in the piece. Provides a measure of how peaked or flat the pitch class distribution is. The higher the kurtosis, the more the pitch classes are clustered near the mean and the fewer outliers there are.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Pitch Class Kurtosis After Folding</name>
      <code>P-32</code>
      <description>Kurtosis of the pitch classes after being folded by perfect fifths as described for the folded fifths pitch class histogram. Provides a measure of how peaked or flat the pitch classes are from a dominant-tonic perspective.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Major or Minor</name>
      <code>P-33</code>
      <description>Whether the piece is major or minor, as indicated by the first encountered major/minor metadata tag in the piece. Set to 0 if the metadata indicates that the piece is major, or set to 1 if the metadata indicates that it is minor. Defaults to 0 if the key signature is unknown.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>First Pitch</name>
      <code>P-34</code>
      <description>The MIDI pitch value of the first note in the piece. If there are multiple notes with simultaneous attacks at the beginning of the piece, then the one with the lowest pitch is selected. Set to 0 if there are no pitched notes.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>First Pitch Class</name>
      <code>P-35</code>
      <description>The pitch class of the first note in the piece. If there are multiple notes with simultaneous attacks at the beginning of the piece, then the one with the lowest pitch is selected. A value of 0 corresponds to C, and pitches increase chromatically by semitone in integer units (e.g. a value of 2 would mean that D is the most common pitch class). Enharmonic equivalents are treated as a single pitch class. Set to 0 if there are no pitched notes.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Last Pitch</name>
      <code>P-36</code>
      <description>The MIDI pitch value of the last note in the piece. If there are multiple notes with simultaneous attacks at the end of the piece, then the one with the lowest pitch is selected. Set to 0 if there are no pitched notes.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Last Pitch Class</name>
      <code>P-37</code>
      <description>The pitch class of the last note in the piece. If there are multiple notes with simultaneous attacks at the end of the piece, then the one with the lowest pitch is selected. A value of 0 corresponds to C, and pitches increase chromatically by semitone in integer units (e.g. a value of 2 would mean that D is the most common pitch class). Enharmonic equivalents are treated as a single pitch class. Set to 0 if there are no pitched notes.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Glissando Prevalence</name>
      <code>P-38</code>
      <description>Number of pitched MIDI Note Ons that have at least one MIDI Pitch Bend associated with them, divided by the total number of pitched Note Ons in the piece.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Average Range of Glissandos</name>
      <code>P-39</code>
      <description>Average range of MIDI Pitch Bends, where "range" is defined as the greatest value of the absolute difference between 64 and the second data byte of all MIDI Pitch Bend messages falling between the Note On and Note Off messages of any note in the piece. Set to 0 if there are no MIDI Pitch Bends in the piece.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Vibrato Prevalence</name>
      <code>P-40</code>
      <description>Number of pitched notes that have associated MIDI Pitch Bend messages change direction at least twice in connection with the note in question, divided by the total number of pitched Note Ons in the piece.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Microtone Prevalence</name>
      <code>P-41</code>
      <description>Number of pitched notes that are each associated with exactly one MIDI Pitch Bend message, divided by the total number of pitched Note Ons in the piece. Set to 0 if there are no pitched Note Ons in the piece.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Melodic Interval Histogram</name>
      <code>M-1</code>
      <description>A feature vector consisting of the bin magnitudes of the melodic interval histogram described above. Each bin corresponds to a melodic interval, and the bin index indicates the number of semitones comprising the interval associated with the bin (there are 128 bins in all). For example, bin 0 corresponds to repeated pitches, bin 1 to a melodic interval of one semitone, bin 2 to a melodic interval of 2 semitones, etc. The magnitude of each bin is proportional to the fraction of melodic intervals in the piece that are of the kind associated with the bin (this histogram is normalized). Rising and falling intervals are treated as identical. Melodies are assumed to be contained within individual MIDI tracks and channels, so melodic intervals are found separately for each track and channel before being combined in this histogram. It is also assumed that there is only one melody at a time per MIDI channel (if multiple notes occur simultaneously on the same MIDI tick on the same MIDI track and channel, then all notes but the first note on that tick are ignored). Other than this, all notes on the same track and the same channel are treated as if they are part of a single melody. It is also assumed that melodies do not cross MIDI tracks or channels (i.e. that they are each separately contained in their own track and channel). Only pitched notes are considered, so all notes on the unpitched MIDI Channel 10 are ignored.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>128</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Most Common Melodic Interval</name>
      <code>M-2</code>
      <description>Number of semitones corresponding to the most frequently occurring melodic interval.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Mean Melodic Interval</name>
      <code>M-3</code>
      <description>Mean average (in semitones) of the intervals involved in each of the melodic intervals in the piece.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Number of Common Melodic Intervals</name>
      <code>M-4</code>
      <description>Number of different melodic intervals that each account individually for at least 9% of all melodic intervals.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Distance Between Most Prevalent Melodic Intervals</name>
      <code>M-5</code>
      <description>Absolute value of the difference (in semitones) between the most common and second most common melodic intervals in the piece.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Prevalence of Most Common Melodic Interval</name>
      <code>M-6</code>
      <description>Fraction of all melodic intervals that corresponds to the most common melodic interval.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Relative Prevalence of Most Common Melodic Intervals</name>
      <code>M-7</code>
      <description>Relative frequency of the second most common melodic interval in the piece, divided by the relative frequency of the most common melodic interval..</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Amount of Arpeggiation</name>
      <code>M-8</code>
      <description>Fraction of melodic intervals that are repeated notes, minor thirds, major thirds, perfect fifths, minor sevenths, major sevenths, octaves, minor tenths or major tenths. This is only a very approximate measure of the amount of arpeggiation in the music, of course.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Repeated Notes</name>
      <code>M-9</code>
      <description>Fraction of melodic intervals that correspond to repeated notes.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Chromatic Motion</name>
      <code>M-10</code>
      <description>Fraction of melodic intervals that correspond to a semitone.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Stepwise Motion</name>
      <code>M-11</code>
      <description>Fraction of melodic intervals that correspond to a minor or major second.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Melodic Thirds</name>
      <code>M-12</code>
      <description>Fraction of melodic intervals that are major or minor thirds.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Melodic Perfect Fourths</name>
      <code>M-13</code>
      <description>Fraction of melodic intervals that are perfect fourths.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Melodic Tritones</name>
      <code>M-14</code>
      <description>Fraction of melodic intervals that are tritones.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Melodic Perfect Fifths</name>
      <code>M-15</code>
      <description>Fraction of melodic intervals that are perfect fifths.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Melodic Sixths</name>
      <code>M-16</code>
      <description>Fraction of melodic intervals that are major or minor sixths.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Melodic Sevenths</name>
      <code>M-17</code>
      <description>Fraction of melodic intervals that are major or minor sevenths.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Melodic Octaves</name>
      <code>M-18</code>
      <description>Fraction of melodic intervals that are octaves.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Melodic Large Intervals</name>
      <code>M-19</code>
      <description>Fraction of melodic intervals greater than one octave.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Minor Major Melodic Third Ratio</name>
      <code>M-20</code>
      <description>Combined fraction of all melodic intervals that are minor thirds, divided by the combined fraction of all melodic intervals that are major thirds. Set to 0 if there are no melodic minor thirds or melodic major thirds.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Melodic Embellishments</name>
      <code>M-21</code>
      <description>Fraction of all notes that are surrounded on both sides by MIDI Note Ons on the same MIDI channel that have durations at least three times as long as the central note. Set to 0 if there are no notes in the piece.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Direction of Melodic Motion</name>
      <code>M-22</code>
      <description>Fraction of melodic intervals that are rising in pitch. Set to zero if no rising or falling melodic intervals are found.</description>
      <is_sequential>true</is_sequential>
      <parallel_dimensions>1</parallel_dimensions>
      <extractor>jSymbolic 2.3</extractor>
   </feature>

   <feature>
      <name>Average Length of Melodic Arcs</name>
      <code>M-23</code>
      <description>Average number of notes that separate melodic peaks and troughs. Similar assumptions are made in the calculation of this feature as for the Melodic Interval Histogram. Set to 0 if no melodic arcs are found.</description>
      <is_sequential>true</is_sequential>